from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.27.1")


##### setup report #####
configfile: "config/config.yaml"


workdir: config.get("paths").get("workdir")


##### load rules #####
include: "rules/common.smk"
include: "rules/raw_data.smk"
include: "rules/umi_qiagen.smk"
include: "rules/trimming.smk"
include: "rules/qc.smk"
include: "rules/mapping.smk"
include: "rules/samtools.smk"
include: "rules/count_mirna.smk"


##### local rules #####
localrules:
    all,


##### target rules #####
rule all:
    input:
        expand(
            resolve_results_filepath(
                config.get("paths").get("results_dir"),
                "reads/counts/{sample.sample}.counts.completed",
            ),
            sample=samples.reset_index().itertuples(),
        ),
        resolve_results_filepath(
            config.get("paths").get("results_dir"), "qc/multiqc.html"
        ),
    threads: conservative_cpu_count(reserve_cores=2, max_cores=99)
    resources:
        tmpdir=config.get("paths").get("tmp_dir"),
    message:
        "Concluding the workflow!"
